name: vertcoin-core
version: 0.18.0
summary:   peer-to-peer network based digital currency
description: |
  Vertcoin is a free open source peer-to-peer electronic cash system that
  is completely decentralized, without the need for a central server or
  trusted parties.  Users hold the crypto keys to their own money and
  transact directly with each other, with the help of a P2P network to
  check for double-spending.

grade: stable
confinement: strict

apps:
  daemon:
    command: vertcoind
    plugs: [home, removable-media, network, network-bind]
    environment:
      # Override HOME so the datadir is located at
      # ~/snap/vertcoin-core/common/.vertcoin/ instead of
      # ~/snap/vertcoin-core/current/.vertcoin/, and each new version of the
      # snap won't have a different data directory:
      # https://docs.snapcraft.io/environment-variables/7983
      HOME: $SNAP_USER_COMMON
  qt:
    command: desktop-launch vertcoin-qt
    plugs: [home, removable-media, network, network-bind, desktop, x11, unity7]
    environment:
      HOME: $SNAP_USER_COMMON
      DISABLE_WAYLAND: 1
  cli:
    command: vertcoin-cli
    plugs: [home, removable-media, network]
    environment:
      HOME: $SNAP_USER_COMMON

parts:
  bitcoin-core:
    plugin: nil
    override-build: | 
      env | grep SNAP
      wget https://raw.githubusercontent.com/vertcoin-project/guix.sigs/main/${SNAPCRAFT_PROJECT_VERSION}/vertion/all.SHA256SUMS
      wget https://github.com/vertcoin-project/vertcoin-core/releases/download/${SNAPCRAFT_PROJECT_VERSION}/vertcoin-${SNAPCRAFT_PROJECT_VERSION}-${SNAPCRAFT_ARCH_TRIPLET}.tar.gz
      echo "e89ac4bbec19b4ac0877259475f3f88f7110495b1247acb00986543782586faa  all.SHA256SUMS" | sha256sum --check
      sha256sum --ignore-missing --check all.SHA256SUMS
      tar -xvf vertcoin-${SNAPCRAFT_PROJECT_VERSION}-${SNAPCRAFT_ARCH_TRIPLET}.tar.gz
      install -m 0755 -D -t $SNAPCRAFT_PART_INSTALL/bin vertcoin-${SNAPCRAFT_PROJECT_VERSION}/bin/vertcoind
      install -m 0755 -D -t $SNAPCRAFT_PART_INSTALL/bin vertcoin-${SNAPCRAFT_PROJECT_VERSION}/bin/vertcoin-qt
      install -m 0755 -D -t $SNAPCRAFT_PART_INSTALL/bin vertcoin-${SNAPCRAFT_PROJECT_VERSION}/bin/vertcoin-cli
      wget https://raw.githubusercontent.com/vertcoin-project/vertcoin-core/${SNAPCRAFT_PROJECT_VERSION}/share/pixmaps/vertcoin128.png
      install -m 0644 -D -t $SNAPCRAFT_PART_INSTALL/share/pixmaps vertcoin128.png
    build-packages:
      - wget
    after:
      - desktop-qt5
